### ISSUE TITLE
Restricted Zuora Bank Transfer Account Number is included in PaymentMethod queries

### ISSUE THREAD

**Issue by cdelrosario** [sportngin/active_zuora#25]
When doing a select on PaymentMethod, the Zuora write-only field BankTransferAccountNumber is included in queries which is causing the query to fail. 

Suggestion, these types of restricted fields should be configurable via config so we do not have to wait for GEM updates to fix them. At the moment we had to enumerate all the fields in our queries, not ideal but it works.

**Comment by anfleene** [comment]
These changes went out. Sorry for the screwup on releasing it initially.
