### ISSUE TITLE
Add Query Limit Functionality

### ISSUE THREAD

**Issue by deanobarnett** [sportngin/active_zuora#28]
There is no way currently to limit the query result set. Something similar to the `order` method would be nice. `..Subscription.where(foo: 'bar').limit(5)`

Zuora Reference => https://knowledgecenter.zuora.com/Z-Sandbox/Zuora_Object_Query_Language/Export_ZOQL/B_ZOQL_Clauses#Limit

**Comment by anfleene** [comment]
We don't support export ZQL I don't think Limit is part of the normal [query call](https://knowledgecenter.zuora.com/D_SOAP_API/E_SOAP_API_Calls/query_call)
