### ISSUE TITLE
Thread Safety on README

### ISSUE THREAD

**Issue by jordanburke** [sportngin/active_zuora#46]
It doesn't look like the Thread Safety is an issue anymore with the newer version of Savon (1.2.0) being used, but the repo README says otherwise. Anyone confirm this?

**Comment by anfleene** [comment]
Yes that is correct I'll update the readme

**Comment by anfleene** [comment]
Updated https://github.com/sportngin/active_zuora/commit/961d7bf4360f7a1ef813867e66fd39946d3692f1

**Comment by jordanburke** [comment]
@anfleene awesome thanks!
