### ISSUE TITLE
Add RevenueRecognitionRuleName to excluded fields for RatePlanCharge

### ISSUE THREAD

**Issue by scottpayne** [sportngin/active_zuora#48]
Hi guys,

Our project has recently needed to upgrade the WSDL to 64.0 and ran into this:

> invalid field for query: RatePlanCharge.RevenueRecognitionRuleName: select Id, AccountingCode, ApplyDiscountTo, BillCycleDay, BillCycleType, BillingPeriod, BillingPeriodAlignment, ChargedThroughDate, ChargeModel, ChargeNumber, ChargeType, CreatedById, CreatedDate, Description, DiscountLevel, DMRC, DTCV, EffectiveEndDate, EffectiveStartDate, IsLastSegment, MRR, Name, NumberOfPeriods, OriginalId, OverageCalculationOption, OverageUnusedUnitsCreditOption, Price, PriceChangeOption, PriceIncreasePercentage, ProcessedThroughDate, ProductRatePlanChargeId, Quantity, RatePlanId, RevenueRecognitionRuleName, RevRecCode, RevRecTriggerCondition, Segment, SpecificBillingPeriod, TCV, TriggerDate, TriggerEvent, UnusedUnitsCreditRates, UOM, UpdatedById, UpdatedDate, UpToPeriods, UsageRecordRatingOption, UseDiscountSpecificAccountingCode, Version from RatePlanCharge where RatePlanId = '...'

I got the following response from Zuora support:

> The field "RevenueRecognitionRuleName" is a field introduced in the WSDL if the feature Z-Finance is enabled in your environment.

> As you've noticed, this field is not supported when executing a query() call against the RatePlanCharge object as there limitations which prevents this field to be exposed as part of the RatePlanCharge query() call.

> Although this field does not support the query() call, it has been made available as part of the RatePlanCharge object as this supports the update() call to modify the current value given that the subscription owning the RatePlan and RatePlanCharge objects is still in a 'Draft' status. Furthermore, the subscribe() call creating a new subscription, RatePlan, and RatePlanCharge object supports passing the field "RevenueRecognitionRuleName" to override the default value set at the ProductRatePlanCharge object.

So to work around I've monkey patched the generated RatePlanCharge object. Would it be possible for you to add this field to the list of excluded query fields for that object?

Thanks,
Scott Payne

**Comment by anfleene** [comment]
Yeah sure no problem.

**Comment by anfleene** [comment]
Fixed via #49  v2.2.6 is out on rubygems.
