### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by pxlpnk** [sportngin/active_zuora#54]
We where just updating our bundle and figured there was an update on this gem.
Unfortunately the CHANGELOG seems to be abandoned. Is there a specific reason for this?

**Comment by anfleene** [comment]
Sorry about this. There isn't a good reason. My deployment workflow hasn't included it recently. It just creates the version entry in the CHANGELOG. I'll try to backdate and make sure it get's updated going forward with our next release.

**Comment by pxlpnk** [comment]
Thank you for taking care of this! :green_heart:

**Comment by pxlpnk** [comment]
There is a changelog now. closing this.
