### ISSUE TITLE
Generate a preview for future Invoice - BillingPreview()

### ISSUE THREAD

**Issue by bharad** [sportngin/active_zuora#61]
Hello,

I have been trying to test the BillingPreview () call and seems like there is no support in active_zuora. Are there any plans to include support for the same ?

Currently these seem to be the only options for anything related to BillingPreview
[:BillingPreviewRequest, :BillingPreviewResult, :BillingPreviewRun]

Alternatively, I tried to use the BillingPreviewRun instead

2.2.0 :016 > bpr = ActiveZuora::BillingPreviewRun.new ({"target_date": "2015-05-31"})

 => #<ActiveZuora::BillingPreviewRun:0x007fc1412f2880 @id=nil, @batch=nil, @charge_type_to_exclude=nil, @created_by_id=nil, @created_date=nil, @end_date=nil, @error_message=nil, @including_evergreen_subscription=nil, @result_file_url=nil, @run_number=nil, @start_date=nil, @status=nil, @succeeded_accounts=nil, @target_date=Sun, 31 May 2015 00:00:00 +0000, @total_accounts=nil, @updated_by_id=nil, @updated_date=nil, @changed_attributes={"target_date"=>nil}>

But ended up getting this...

2.2.0 :018 >   bpr.create
NoMethodError: private method `create' called for #<ActiveZuora::BillingPreviewRun:0x007fc1412f2880>

Appreciate any help or feedback on this issue. Thanks!

**Comment by jonnymacs** [comment]
@bharad I've added support for BillingPreviewRequest#billing_preview on my fork.  I'm going to issue a pull request now to have it merged.

**Comment by jonnymacs** [comment]
@bharad actually now I look more there is a slightly better implementation with a pending pull request for this feature completed by @jconley88

https://github.com/sportngin/active_zuora/pull/58/commits

I'm going to merge these into my branch for for now as well.

@anfleene what do you think about merging this pr?

**Comment by anfleene** [comment]
at a glance it looks fine. It doesn't merge cleanly with master so that would need to be cleaned up first. I'm not sure what the conflicts would be from though.

**Comment by jonnymacs** [comment]
@anfleene https://github.com/sportngin/active_zuora/pull/62

**Comment by anfleene** [comment]
AZ 2.3.1 is out on rubygems with support for BillingPreview. Thanks @jonnymacs  and @jconley88 for your work on this!
