### ISSUE TITLE
Unknown Field type: date

### ISSUE THREAD

**Issue by blade2005** [sportngin/active_zuora#63]
I receive the following error multiple times when generating classes: 
Unknown field type: date

Here is a snippet from object ProductRatePlan (wsdl 73.0)
<element minOccurs="0" name="EffectiveEndDate" nillable="true" type="date"  />
<element minOccurs="0" name="EffectiveStartDate" nillable="true" type="date" />

I think these should fall under datetime.

Based on the code the change should be made in I think
https://github.com/sportngin/active_zuora/blob/master/lib/active_zuora/fields.rb#L103

But when I changed it and added a line stating date as the symbol it continued to complain about that field type after deploying the changed gem.

Did I miss somewhere else that it should be changed? I'm happy to make a PR to fix this I just can't find where I need to change it.

**Comment by blade2005** [comment]
I also saw https://github.com/sportngin/active_zuora/blob/f7adf307d680efafda84a6b7aab5da4f1d00fbcf/lib/active_zuora/generator.rb#L68 and added a section for date but this didn't resolve the issue.

**Comment by blade2005** [comment]
Apparently in my testing I did not proper install it with root, Making commit and submitting PR

**Comment by anfleene** [comment]
This should be resolved by #56 which is in version 2.4 on rubygems.
