### ISSUE TITLE
ActiveSupport/ActiveModel 5 compatibility

### ISSUE THREAD

**Issue by sisk** [sportngin/active_zuora#74]
I'm trying to integrate this gem into a Rails 5 application, but noticed it's [not compatible yet](https://github.com/sportngin/active_zuora/blob/master/active_zuora.gemspec#L25-L26). Has anyone identified yet what would be necessary to bring it up to date?

(also: Hi Andy!)

**Comment by anfleene** [comment]
Hah! Hi @sisk and No Not that I know of.

**Comment by anfleene** [comment]
It might work. Open to relaxing the constraint if you give it a shot and it works.

**Comment by sisk** [comment]
I did [this](https://github.com/sisk/active_zuora/commit/b97c725683d5b9ed24786bb4b67c9f00e9adbd59) and no specs failed (yet).

**Comment by anfleene** [comment]
Sweet!

**Comment by jonnymacs** [comment]
@anfleene @sisk - gonna need this pretty soon.  I merged b97c725 to a branch off master and I'm running it in a rails5 application.  Will be testing for the next week or so, I'll keep you posted.

**Comment by sisk** [comment]
FWIW, Belly has been running that code on a fork in production now for well over a month with no issues.

**Comment by anfleene** [comment]
@sisk Want to contribute your spec change? I can merge and release a rails 5 compatible version.

**Comment by sisk** [comment]
I didn't make any spec change. We just rolled it out slowly enough to watch for regressions, and have seen none.

**Comment by anfleene** [comment]
Heh sorry I meant gemspec.

**Comment by jonnymacs** [comment]
ok a clean install of this gem after this change will require ruby 2.2.2 or newer.

@anfleene how important is support for the older versions of ruby?

**Comment by anfleene** [comment]
Why's that? I'd prefer not to drop that many versions all at once. I'm not sure how relaxing the AS/AM restriction would change much though.

**Comment by anfleene** [comment]
Thanks @sisk! [2.5.0](https://rubygems.org/gems/active_zuora/versions/2.5.0) is out on rubygems.

**Comment by jonnymacs** [comment]
@anfleene @sisk 👍   Thanks for getting this merged and released.

On a clean install bundler will now fetch AS/AM 5.0.0.1 which requires 2.2.2+  Obviously the gem still works with older ruby if < 5.0 AS / AM is installed already.  2.2.2 is over 18 months old now, so it doesn't bother me.
