### ISSUE TITLE
Rails 5.1

### ISSUE THREAD

**Issue by timpbrenner** [sportngin/active_zuora#79]
I would like to use this gem on a rails 5.1 branch. Based on a local branch I believe that updating the dependencies for activesupport and activemodel should suffice.

**Comment by TheTeaNerd** [comment]
:+1: Is there a release plan for a Rails 5.1 version? (Or should I think about a PR?)

**Comment by anfleene** [comment]
No plans for us at the moment, but I would gladly accept a PR

**Comment by timpbrenner** [comment]
@anfleene In this PR: https://github.com/sportngin/active_zuora/pull/81 I removed the upper bound for the Rails gem. I have been running this branch in our app for the last 6 months and have had no issues.

**Comment by anfleene** [comment]
2.5.3 is out on Rubygems! Thanks @timpbrenner!
