### ISSUE TITLE
Support For Batched Creates

### ISSUE THREAD

**Issue by timsegraves** [sportngin/active_zuora#8]
It doesn't appear that this gem supports batched creates.  Am I correct in this assumption?  The update function in the persistance class looks like it does batch updates but I don't see a way to do batched creates.

Please let me know if I'm missing this functionality, otherwise I may look at adding this functionality if we go with this gem.  Thanks.

**Comment by jonnymacs** [comment]
I'm working on a PR for this.  Should have something shortly.
